//go:build !ignore_autogenerated

// Code generated by hack/gen-namespaced.sh. DO NOT EDIT.

package v1alpha1ns

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

func (in *LocalSecretReference) DeepCopyInto(out *LocalSecretReference) { *out = *in }
func (in *LocalSecretReference) DeepCopy() *LocalSecretReference {
	if in == nil { return nil }
	out := new(LocalSecretReference)
	*out = *in
	return out
}

func (in *ProviderConfigReference) DeepCopyInto(out *ProviderConfigReference) { *out = *in }
func (in *ProviderConfigReference) DeepCopy() *ProviderConfigReference {
	if in == nil { return nil }
	out := new(ProviderConfigReference)
	*out = *in
	return out
}

func (in *NamespacedSpec) DeepCopyInto(out *NamespacedSpec) {
	*out = *in
	if in.WriteConnectionSecretToReference != nil {
		in, out := &in.WriteConnectionSecretToReference, &out.WriteConnectionSecretToReference
		*out = new(LocalSecretReference)
		**out = **in
	}
	if in.ProviderConfigReference != nil {
		in, out := &in.ProviderConfigReference, &out.ProviderConfigReference
		*out = new(ProviderConfigReference)
		**out = **in
	}
	if in.ManagementPolicies != nil {
		in, out := &in.ManagementPolicies, &out.ManagementPolicies
		*out = make(xpv1.ManagementPolicies, len(*in))
		copy(*out, *in)
	}
}

func (in *NamespacedSpec) DeepCopy() *NamespacedSpec {
	if in == nil { return nil }
	out := new(NamespacedSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *NamespacedStatus) DeepCopyInto(out *NamespacedStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
}

func (in *NamespacedStatus) DeepCopy() *NamespacedStatus {
	if in == nil { return nil }
	out := new(NamespacedStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *DBInstanceSpec) DeepCopyInto(out *DBInstanceSpec) {
	*out = *in
	in.NamespacedSpec.DeepCopyInto(&out.NamespacedSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

func (in *DBInstanceSpec) DeepCopy() *DBInstanceSpec {
	if in == nil { return nil }
	out := new(DBInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *DBInstanceStatus) DeepCopyInto(out *DBInstanceStatus) {
	*out = *in
	in.NamespacedStatus.DeepCopyInto(&out.NamespacedStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

func (in *DBInstanceStatus) DeepCopy() *DBInstanceStatus {
	if in == nil { return nil }
	out := new(DBInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *DBInstance) DeepCopyInto(out *DBInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *DBInstance) DeepCopy() *DBInstance {
	if in == nil { return nil }
	out := new(DBInstance)
	in.DeepCopyInto(out)
	return out
}

func (in *DBInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *DBInstanceList) DeepCopyInto(out *DBInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DBInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *DBInstanceList) DeepCopy() *DBInstanceList {
	if in == nil { return nil }
	out := new(DBInstanceList)
	in.DeepCopyInto(out)
	return out
}

func (in *DBInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *DBClusterSpec) DeepCopyInto(out *DBClusterSpec) {
	*out = *in
	in.NamespacedSpec.DeepCopyInto(&out.NamespacedSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

func (in *DBClusterSpec) DeepCopy() *DBClusterSpec {
	if in == nil { return nil }
	out := new(DBClusterSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *DBClusterStatus) DeepCopyInto(out *DBClusterStatus) {
	*out = *in
	in.NamespacedStatus.DeepCopyInto(&out.NamespacedStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

func (in *DBClusterStatus) DeepCopy() *DBClusterStatus {
	if in == nil { return nil }
	out := new(DBClusterStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *DBCluster) DeepCopyInto(out *DBCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *DBCluster) DeepCopy() *DBCluster {
	if in == nil { return nil }
	out := new(DBCluster)
	in.DeepCopyInto(out)
	return out
}

func (in *DBCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *DBClusterList) DeepCopyInto(out *DBClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DBCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *DBClusterList) DeepCopy() *DBClusterList {
	if in == nil { return nil }
	out := new(DBClusterList)
	in.DeepCopyInto(out)
	return out
}

func (in *DBClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *DBParameterGroupSpec) DeepCopyInto(out *DBParameterGroupSpec) {
	*out = *in
	in.NamespacedSpec.DeepCopyInto(&out.NamespacedSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

func (in *DBParameterGroupSpec) DeepCopy() *DBParameterGroupSpec {
	if in == nil { return nil }
	out := new(DBParameterGroupSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *DBParameterGroupStatus) DeepCopyInto(out *DBParameterGroupStatus) {
	*out = *in
	in.NamespacedStatus.DeepCopyInto(&out.NamespacedStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

func (in *DBParameterGroupStatus) DeepCopy() *DBParameterGroupStatus {
	if in == nil { return nil }
	out := new(DBParameterGroupStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *DBParameterGroup) DeepCopyInto(out *DBParameterGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *DBParameterGroup) DeepCopy() *DBParameterGroup {
	if in == nil { return nil }
	out := new(DBParameterGroup)
	in.DeepCopyInto(out)
	return out
}

func (in *DBParameterGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *DBParameterGroupList) DeepCopyInto(out *DBParameterGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DBParameterGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *DBParameterGroupList) DeepCopy() *DBParameterGroupList {
	if in == nil { return nil }
	out := new(DBParameterGroupList)
	in.DeepCopyInto(out)
	return out
}

func (in *DBParameterGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *DBClusterParameterGroupSpec) DeepCopyInto(out *DBClusterParameterGroupSpec) {
	*out = *in
	in.NamespacedSpec.DeepCopyInto(&out.NamespacedSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

func (in *DBClusterParameterGroupSpec) DeepCopy() *DBClusterParameterGroupSpec {
	if in == nil { return nil }
	out := new(DBClusterParameterGroupSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *DBClusterParameterGroupStatus) DeepCopyInto(out *DBClusterParameterGroupStatus) {
	*out = *in
	in.NamespacedStatus.DeepCopyInto(&out.NamespacedStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

func (in *DBClusterParameterGroupStatus) DeepCopy() *DBClusterParameterGroupStatus {
	if in == nil { return nil }
	out := new(DBClusterParameterGroupStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *DBClusterParameterGroup) DeepCopyInto(out *DBClusterParameterGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *DBClusterParameterGroup) DeepCopy() *DBClusterParameterGroup {
	if in == nil { return nil }
	out := new(DBClusterParameterGroup)
	in.DeepCopyInto(out)
	return out
}

func (in *DBClusterParameterGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *DBClusterParameterGroupList) DeepCopyInto(out *DBClusterParameterGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DBClusterParameterGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *DBClusterParameterGroupList) DeepCopy() *DBClusterParameterGroupList {
	if in == nil { return nil }
	out := new(DBClusterParameterGroupList)
	in.DeepCopyInto(out)
	return out
}

func (in *DBClusterParameterGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *DBInstanceRoleAssociationSpec) DeepCopyInto(out *DBInstanceRoleAssociationSpec) {
	*out = *in
	in.NamespacedSpec.DeepCopyInto(&out.NamespacedSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

func (in *DBInstanceRoleAssociationSpec) DeepCopy() *DBInstanceRoleAssociationSpec {
	if in == nil { return nil }
	out := new(DBInstanceRoleAssociationSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *DBInstanceRoleAssociationStatus) DeepCopyInto(out *DBInstanceRoleAssociationStatus) {
	*out = *in
	in.NamespacedStatus.DeepCopyInto(&out.NamespacedStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

func (in *DBInstanceRoleAssociationStatus) DeepCopy() *DBInstanceRoleAssociationStatus {
	if in == nil { return nil }
	out := new(DBInstanceRoleAssociationStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *DBInstanceRoleAssociation) DeepCopyInto(out *DBInstanceRoleAssociation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *DBInstanceRoleAssociation) DeepCopy() *DBInstanceRoleAssociation {
	if in == nil { return nil }
	out := new(DBInstanceRoleAssociation)
	in.DeepCopyInto(out)
	return out
}

func (in *DBInstanceRoleAssociation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *DBInstanceRoleAssociationList) DeepCopyInto(out *DBInstanceRoleAssociationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DBInstanceRoleAssociation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *DBInstanceRoleAssociationList) DeepCopy() *DBInstanceRoleAssociationList {
	if in == nil { return nil }
	out := new(DBInstanceRoleAssociationList)
	in.DeepCopyInto(out)
	return out
}

func (in *DBInstanceRoleAssociationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *GlobalClusterSpec) DeepCopyInto(out *GlobalClusterSpec) {
	*out = *in
	in.NamespacedSpec.DeepCopyInto(&out.NamespacedSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

func (in *GlobalClusterSpec) DeepCopy() *GlobalClusterSpec {
	if in == nil { return nil }
	out := new(GlobalClusterSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *GlobalClusterStatus) DeepCopyInto(out *GlobalClusterStatus) {
	*out = *in
	in.NamespacedStatus.DeepCopyInto(&out.NamespacedStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

func (in *GlobalClusterStatus) DeepCopy() *GlobalClusterStatus {
	if in == nil { return nil }
	out := new(GlobalClusterStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *GlobalCluster) DeepCopyInto(out *GlobalCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *GlobalCluster) DeepCopy() *GlobalCluster {
	if in == nil { return nil }
	out := new(GlobalCluster)
	in.DeepCopyInto(out)
	return out
}

func (in *GlobalCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *GlobalClusterList) DeepCopyInto(out *GlobalClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GlobalCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *GlobalClusterList) DeepCopy() *GlobalClusterList {
	if in == nil { return nil }
	out := new(GlobalClusterList)
	in.DeepCopyInto(out)
	return out
}

func (in *GlobalClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *OptionGroupSpec) DeepCopyInto(out *OptionGroupSpec) {
	*out = *in
	in.NamespacedSpec.DeepCopyInto(&out.NamespacedSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

func (in *OptionGroupSpec) DeepCopy() *OptionGroupSpec {
	if in == nil { return nil }
	out := new(OptionGroupSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *OptionGroupStatus) DeepCopyInto(out *OptionGroupStatus) {
	*out = *in
	in.NamespacedStatus.DeepCopyInto(&out.NamespacedStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

func (in *OptionGroupStatus) DeepCopy() *OptionGroupStatus {
	if in == nil { return nil }
	out := new(OptionGroupStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *OptionGroup) DeepCopyInto(out *OptionGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *OptionGroup) DeepCopy() *OptionGroup {
	if in == nil { return nil }
	out := new(OptionGroup)
	in.DeepCopyInto(out)
	return out
}

func (in *OptionGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *OptionGroupList) DeepCopyInto(out *OptionGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OptionGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *OptionGroupList) DeepCopy() *OptionGroupList {
	if in == nil { return nil }
	out := new(OptionGroupList)
	in.DeepCopyInto(out)
	return out
}

func (in *OptionGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}
