---
workflow:
  rules:
    # Run on tags
    - if: $CI_COMMIT_TAG

stages:
  - lint
  - build

.base:
  image: tde-green-public-docker-local.artifactory.swisscom.com/go-with-up-cli:1.21.2-bookworm-0.19.2
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    KUBERNETES_CPU_REQUEST: "6"
    KUBERNETES_CPU_LIMIT: "6"
    KUBERNETES_MEMORY_REQUEST: "8Gi"
    KUBERNETES_MEMORY_LIMIT: "8Gi"
    HTTPS_PROXY: http://server-proxy.corprouot.net:8080
    HTTP_PROXY: http://server-proxy.corproot.net:8080
    NO_PROXY: '127.0.0.1,localhost,code.swisscom.com,git.swisscom.com,artifactory.swisscom.com,bin.swisscom.com,icp.swisscom.com'
    GOFLAGS: '-buildvcs=false'
    GOPROXY: "https://artifactory.swisscom.com/artifactory/api/go/proxy-golang-go-virtual"
    GOARCH: amd64
    CGO_ENABLED: 0
    GOOS: linux
    http_proxy: http://server-proxy.corproot.net:8080
    https_proxy: http://server-proxy.corproot.net:8080
    noproxy: '127.0.0.1,localhost,code.swisscom.com,git.swisscom.com,artifactory.swisscom.com,bin.swisscom.com,icp.swisscom.com'
    GOFLAGS: '-buildvcs=false'
  script:
    - mkdir -p $HOME/.docker && cat $DOCKER_CONFIG_JSON > $HOME/.docker/config.json
    - git config --global --add safe.directory $CI_PROJECT_DIR

lint:
  stage: lint
  extends: .base
  allow_failure: true
  script:
    - |
      sed  -i -e '3s/^$/  concurrency\: 6/g' .golangci.yml
      cat .golangci.yml
      make vendor vendor.check

build:
  stage: build
  extends: .base
  variables:
    TOOLS_DIR: ${CI_PROJECT_DIR}/.cache/tools/linux_amd64
  script:
    - |
      if [[ $CI_COMMIT_TAG =~ ^v?[0-9]{1,4}.[0-9]{1,4}.[0-9]{1,4}$ ]]; then
        export DESTINATION_REGISTRY=tde-green-public-docker-local.artifactory.swisscom.com
        BUILD_TYPE=release
      else
        export DESTINATION_REGISTRY=crossplane-dev-docker-local.artifactory.swisscom.com
        BUILD_TYPE=development
      fi
      echo "this build classified as ${BUILD_TYPE} based on tag ${CI_COMMIT_TAG}"
    - |
      mkdir -p  ${TOOLS_DIR}
      cp ./up ${TOOLS_DIR}/up-v0.18.0
    - make build VERSION=$CI_COMMIT_TAG
    - make publish.artifacts PLATFORMS=linux_amd64 XPKG_REG_ORGS=${DESTINATION_REGISTRY}/provider-aws VERSION=${CI_COMMIT_TAG}
