---
apiVersion: rds.aws.crossplane.io/v1alpha1
kind: DBInstance
metadata:
  name: example-read-replica-1
spec:
  forProvider:
    region: eu-central-1
    replicateSourceDBInstanceID: example-dbinstance
    engine: mariadb
    dbInstanceClass: db.t3.micro
    autoMinorVersionUpgrade: true
    allowMajorVersionUpgrade: true # unset per default (Note: supported dbInstanceClass and dbParameterGroup with correct dbParameterGroupFamily needed, before majorVersion upgrade possible; applyImmediately matters)
    applyImmediately: true
    skipFinalSnapshot: true
#    masterUserPasswordSecretRef:
#      key: password
#      name: replica-test
#      namespace: default
  writeConnectionSecretToRef:
    name: example-read-replica-1
    namespace: default
  providerConfigRef:
    name: provider-aws

# By default, the read replica has the master user credentials as the source database.
#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name:  replica-test
#  namespace: default
#type: Opaque
#data:
#  password: dGVzdFBhc3N3b3JkITEyMw== # testPassword!123
