//go:build !ignore_autogenerated

// Code generated by hack/gen-namespaced.sh. DO NOT EDIT.

package v1beta1ns

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

func (in *LocalSecretReference) DeepCopyInto(out *LocalSecretReference) { *out = *in }
func (in *LocalSecretReference) DeepCopy() *LocalSecretReference {
	if in == nil { return nil }
	out := new(LocalSecretReference)
	*out = *in
	return out
}

func (in *ProviderConfigReference) DeepCopyInto(out *ProviderConfigReference) { *out = *in }
func (in *ProviderConfigReference) DeepCopy() *ProviderConfigReference {
	if in == nil { return nil }
	out := new(ProviderConfigReference)
	*out = *in
	return out
}

func (in *NamespacedSpec) DeepCopyInto(out *NamespacedSpec) {
	*out = *in
	if in.WriteConnectionSecretToReference != nil {
		in, out := &in.WriteConnectionSecretToReference, &out.WriteConnectionSecretToReference
		*out = new(LocalSecretReference)
		**out = **in
	}
	if in.ProviderConfigReference != nil {
		in, out := &in.ProviderConfigReference, &out.ProviderConfigReference
		*out = new(ProviderConfigReference)
		**out = **in
	}
	if in.ManagementPolicies != nil {
		in, out := &in.ManagementPolicies, &out.ManagementPolicies
		*out = make(xpv1.ManagementPolicies, len(*in))
		copy(*out, *in)
	}
}

func (in *NamespacedSpec) DeepCopy() *NamespacedSpec {
	if in == nil { return nil }
	out := new(NamespacedSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *NamespacedStatus) DeepCopyInto(out *NamespacedStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
}

func (in *NamespacedStatus) DeepCopy() *NamespacedStatus {
	if in == nil { return nil }
	out := new(NamespacedStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *DBSubnetGroupSpec) DeepCopyInto(out *DBSubnetGroupSpec) {
	*out = *in
	in.NamespacedSpec.DeepCopyInto(&out.NamespacedSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

func (in *DBSubnetGroupSpec) DeepCopy() *DBSubnetGroupSpec {
	if in == nil { return nil }
	out := new(DBSubnetGroupSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *DBSubnetGroupStatus) DeepCopyInto(out *DBSubnetGroupStatus) {
	*out = *in
	in.NamespacedStatus.DeepCopyInto(&out.NamespacedStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

func (in *DBSubnetGroupStatus) DeepCopy() *DBSubnetGroupStatus {
	if in == nil { return nil }
	out := new(DBSubnetGroupStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *DBSubnetGroup) DeepCopyInto(out *DBSubnetGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *DBSubnetGroup) DeepCopy() *DBSubnetGroup {
	if in == nil { return nil }
	out := new(DBSubnetGroup)
	in.DeepCopyInto(out)
	return out
}

func (in *DBSubnetGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *DBSubnetGroupList) DeepCopyInto(out *DBSubnetGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DBSubnetGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *DBSubnetGroupList) DeepCopy() *DBSubnetGroupList {
	if in == nil { return nil }
	out := new(DBSubnetGroupList)
	in.DeepCopyInto(out)
	return out
}

func (in *DBSubnetGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}
