#!/usr/bin/env bash
# hack/gen-namespaced-extra.sh
#
# Generates namespaced (Crossplane v2) controllers for non-RDS resources:
#   - ResourceRecordSet (route53)
#   - DBSubnetGroup (database)
#   - SecurityGroup (ec2)
#
# API type packages (apis/*/v1*ns/) are created separately and not regenerated by this script.
# This script only regenerates the controller copies.
#
# Usage: ./hack/gen-namespaced-extra.sh

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

echo "==> Generating ResourceRecordSet ns controller..."
mkdir -p pkg/controller/route53/resourcerecordset_ns
sed \
  -e 's/^package resourcerecordset$/package resourcerecordset_ns/' \
  -e '/^import/,/^)/{
    s|route53v1alpha1 "github.com/crossplane-contrib/provider-aws/apis/route53/v1alpha1"|route53v1alpha1 "github.com/crossplane-contrib/provider-aws/apis/route53/v1alpha1"\
\tnsapitypes "github.com/crossplane-contrib/provider-aws/apis/route53/v1alpha1ns"|
  }' \
  -e 's|\*route53v1alpha1\.ResourceRecordSet\([^A-Za-z0-9_]\)|\*nsapitypes.ResourceRecordSet\1|g' \
  -e 's|\*route53v1alpha1\.ResourceRecordSet$|\*nsapitypes.ResourceRecordSet|g' \
  -e 's|route53v1alpha1\.ResourceRecordSetGroupKind|nsapitypes.ResourceRecordSetGroupKind|g' \
  -e 's|route53v1alpha1\.ResourceRecordSetGroupVersionKind|nsapitypes.ResourceRecordSetGroupVersionKind|g' \
  -e 's|&route53v1alpha1\.ResourceRecordSet{}|\&nsapitypes.ResourceRecordSet{}|g' \
  pkg/controller/route53/resourcerecordset/controller.go > pkg/controller/route53/resourcerecordset_ns/controller.go
# Remove unused import if all references replaced
if ! grep -v 'route53v1alpha1 "' pkg/controller/route53/resourcerecordset_ns/controller.go | grep -q 'route53v1alpha1\.'; then
  sed -i '' '/route53v1alpha1 "github.com\/crossplane-contrib\/provider-aws\/apis\/route53\/v1alpha1"/d' pkg/controller/route53/resourcerecordset_ns/controller.go
fi

echo "==> Generating DBSubnetGroup ns controller..."
mkdir -p pkg/controller/database/dbsubnetgroup_ns
sed \
  -e 's/^package dbsubnetgroup$/package dbsubnetgroup_ns/' \
  -e '/^import/,/^)/{
    s|"github.com/crossplane-contrib/provider-aws/apis/database/v1beta1"|"github.com/crossplane-contrib/provider-aws/apis/database/v1beta1"\
\tnsapitypes "github.com/crossplane-contrib/provider-aws/apis/database/v1beta1ns"|
  }' \
  -e 's|\*v1beta1\.DBSubnetGroup\([^A-Za-z0-9_]\)|\*nsapitypes.DBSubnetGroup\1|g' \
  -e 's|\*v1beta1\.DBSubnetGroup$|\*nsapitypes.DBSubnetGroup|g' \
  -e 's|v1beta1\.DBSubnetGroupGroupKind|nsapitypes.DBSubnetGroupGroupKind|g' \
  -e 's|v1beta1\.DBSubnetGroupGroupVersionKind|nsapitypes.DBSubnetGroupGroupVersionKind|g' \
  -e 's|&v1beta1\.DBSubnetGroup{}|\&nsapitypes.DBSubnetGroup{}|g' \
  pkg/controller/database/dbsubnetgroup/controller.go > pkg/controller/database/dbsubnetgroup_ns/controller.go
# Remove unused import if all references replaced
count=$(grep -v '"github.com/crossplane-contrib/provider-aws/apis/database/v1beta1"' pkg/controller/database/dbsubnetgroup_ns/controller.go | grep -c 'v1beta1\.' || true)
if [[ "$count" -eq 0 ]]; then
  sed -i '' '/"github.com\/crossplane-contrib\/provider-aws\/apis\/database\/v1beta1"/d' pkg/controller/database/dbsubnetgroup_ns/controller.go
fi

echo "==> Generating SecurityGroup ns controller..."
mkdir -p pkg/controller/ec2/securitygroup_ns
sed \
  -e 's/^package securitygroup$/package securitygroup_ns/' \
  -e '/^import/,/^)/{
    s|"github.com/crossplane-contrib/provider-aws/apis/ec2/v1beta1"|"github.com/crossplane-contrib/provider-aws/apis/ec2/v1beta1"\
\tnsapitypes "github.com/crossplane-contrib/provider-aws/apis/ec2/v1beta1ns"|
  }' \
  -e 's|\*v1beta1\.SecurityGroup\([^A-Za-z0-9_]\)|\*nsapitypes.SecurityGroup\1|g' \
  -e 's|\*v1beta1\.SecurityGroup$|\*nsapitypes.SecurityGroup|g' \
  -e 's|v1beta1\.SecurityGroupGroupKind|nsapitypes.SecurityGroupGroupKind|g' \
  -e 's|v1beta1\.SecurityGroupGroupVersionKind|nsapitypes.SecurityGroupGroupVersionKind|g' \
  -e 's|&v1beta1\.SecurityGroup{}|\&nsapitypes.SecurityGroup{}|g' \
  pkg/controller/ec2/securitygroup/controller.go > pkg/controller/ec2/securitygroup_ns/controller.go
# Remove unused import if all references replaced
count=$(grep -v '"github.com/crossplane-contrib/provider-aws/apis/ec2/v1beta1"' pkg/controller/ec2/securitygroup_ns/controller.go | grep -c 'v1beta1\.' || true)
if [[ "$count" -eq 0 ]]; then
  sed -i '' '/"github.com\/crossplane-contrib\/provider-aws\/apis\/ec2\/v1beta1"/d' pkg/controller/ec2/securitygroup_ns/controller.go
fi

echo ""
echo "==> Verifying build..."
if go build ./pkg/controller/route53/resourcerecordset_ns/ ./pkg/controller/database/dbsubnetgroup_ns/ ./pkg/controller/ec2/securitygroup_ns/ 2>&1 | tee /dev/stderr | grep -q "^#"; then
  echo "WARNING: Build errors detected."
  exit 1
else
  echo "OK: All namespaced extra controllers compile."
fi
