---
apiVersion: wafv2.aws.crossplane.io/v1alpha1
kind: WebACL
metadata:
  name: kir-test
    #  annotations:
    #    crossplane.io/external-name: kir-test
spec:
  forProvider:
    name: kir-test
    region: eu-central-1
    rules:
      - name: rule1
        visibilityConfig:
          metricName: 'kir-test'
          sampledRequestsEnabled: false
          cloudWatchMetricsEnabled: false
        priority: 1
        action:
          allow: { }
        statement:
          andStatement: |
            {
              "Statements": [
                {
                  "ByteMatchStatement":
                    {
                      "FieldToMatch": {
                        "SingleHeader": {
                          "Name": "user-agent"
                        }
                      },
                      "PositionalConstraint": "CONTAINS",
                      "SearchString": "bmV3VmFsdWUh",
                      "TextTransformations": [
                        {
                          "Priority": 0,
                          "Type": "NONE"
                        }
                      ]
                    }
                },
                {
                  "ByteMatchStatement":
                    {
                      "FieldToMatch": {
                        "SingleHeader": {
                          "Name": "User-AgentCustim"
                        }
                      },
                      "PositionalConstraint": "CONTAINS",
                      "SearchString": "YmFkQm90",
                      "TextTransformations": [
                        {
                          "Priority": 1,
                          "Type": "NONE"
                        }
                      ]
                    }
                }
              ]
            }
    visibilityConfig:
      metricName: 'kir-test'
      sampledRequestsEnabled: false
      cloudWatchMetricsEnabled: false
    defaultAction:
      allow: { }
    scope: REGIONAL
    tags:
      - key: "crossplane:managed"
        value: "true"
  providerConfigRef:
    name: providerconfig-aws
