---
apiVersion: glue.aws.crossplane.io/v1alpha1
kind: Trigger
metadata:
  name: glue-trigger
spec:
  forProvider:
    region: eu-central-1
    actions:
      - jobName: "test"
        timeout: 2
    description: "Trigger for Glue"
    triggerType: SCHEDULED
    schedule: "cron(*/30 * * * ? *)"
    startOnCreation: true
    tags:
      created-by: crossplane
  providerConfigRef:
    name: providerconfig-aws
