//go:build !ignore_autogenerated

// Code generated by hack/gen-namespaced.sh. DO NOT EDIT.

package v1alpha1ns

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

func (in *LocalSecretReference) DeepCopyInto(out *LocalSecretReference) { *out = *in }
func (in *LocalSecretReference) DeepCopy() *LocalSecretReference {
	if in == nil { return nil }
	out := new(LocalSecretReference)
	*out = *in
	return out
}

func (in *ProviderConfigReference) DeepCopyInto(out *ProviderConfigReference) { *out = *in }
func (in *ProviderConfigReference) DeepCopy() *ProviderConfigReference {
	if in == nil { return nil }
	out := new(ProviderConfigReference)
	*out = *in
	return out
}

func (in *NamespacedSpec) DeepCopyInto(out *NamespacedSpec) {
	*out = *in
	if in.WriteConnectionSecretToReference != nil {
		in, out := &in.WriteConnectionSecretToReference, &out.WriteConnectionSecretToReference
		*out = new(LocalSecretReference)
		**out = **in
	}
	if in.ProviderConfigReference != nil {
		in, out := &in.ProviderConfigReference, &out.ProviderConfigReference
		*out = new(ProviderConfigReference)
		**out = **in
	}
	if in.ManagementPolicies != nil {
		in, out := &in.ManagementPolicies, &out.ManagementPolicies
		*out = make(xpv1.ManagementPolicies, len(*in))
		copy(*out, *in)
	}
}

func (in *NamespacedSpec) DeepCopy() *NamespacedSpec {
	if in == nil { return nil }
	out := new(NamespacedSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *NamespacedStatus) DeepCopyInto(out *NamespacedStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
}

func (in *NamespacedStatus) DeepCopy() *NamespacedStatus {
	if in == nil { return nil }
	out := new(NamespacedStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *ResourceRecordSetSpec) DeepCopyInto(out *ResourceRecordSetSpec) {
	*out = *in
	in.NamespacedSpec.DeepCopyInto(&out.NamespacedSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

func (in *ResourceRecordSetSpec) DeepCopy() *ResourceRecordSetSpec {
	if in == nil { return nil }
	out := new(ResourceRecordSetSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ResourceRecordSetStatus) DeepCopyInto(out *ResourceRecordSetStatus) {
	*out = *in
	in.NamespacedStatus.DeepCopyInto(&out.NamespacedStatus)
}

func (in *ResourceRecordSetStatus) DeepCopy() *ResourceRecordSetStatus {
	if in == nil { return nil }
	out := new(ResourceRecordSetStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *ResourceRecordSet) DeepCopyInto(out *ResourceRecordSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ResourceRecordSet) DeepCopy() *ResourceRecordSet {
	if in == nil { return nil }
	out := new(ResourceRecordSet)
	in.DeepCopyInto(out)
	return out
}

func (in *ResourceRecordSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *ResourceRecordSetList) DeepCopyInto(out *ResourceRecordSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ResourceRecordSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ResourceRecordSetList) DeepCopy() *ResourceRecordSetList {
	if in == nil { return nil }
	out := new(ResourceRecordSetList)
	in.DeepCopyInto(out)
	return out
}

func (in *ResourceRecordSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}
