---
ignore:
  resource_names:
    - APIKey
    - IPSet
    - RegexPatternSet
    - RuleGroup
  field_paths:
    - CreateWebACLInput.Name
    - UpdateWebACLInput.Name
    - DeleteWebACLInput.Name
    - GetWebACLInput.Name
    - WebACL.Rules.Statement.AndStatement
    - WebACL.Rules.Statement.OrStatement
    - WebACL.Rules.Statement.NotStatement
    - WebACL.Rules.Statement.ManagedRuleGroupStatement.ScopeDownStatement
    - WebACL.Rules.Statement.RateBasedStatement.ScopeDownStatement
empty_shapes:
  - All
  - Method
  - UriPath
  - QueryString
  - AllQueryArguments
  - RateLimitIP
  - RateLimitForwardedIP
  - RateLimitHTTPMethod
  - NoneAction
operations:
  GetWebACL:
    output_wrapper_field_path: WebACL
resources:
  WebACL:
    fields:
      Rules.Statement.AndStatement:
        type: string
        set:
          - ignore: "all"
      Rules.Statement.OrStatement:
        type: string
        set:
          - ignore: "all"
      Rules.Statement.NotStatement:
        type: string
        set:
          - ignore: "all"
      Rules.Statement.ManagedRuleGroupStatement.ScopeDownStatement:
        type: string
        set:
          - ignore: "all"
      Rules.Statement.RateBasedStatement.ScopeDownStatement:
        type: string
        set:
          - ignore: "all"
      Rules.Statement.ByteMatchStatement.TextTransformations.Type:
        go_tag: json:"type,omitempty"
    exceptions:
      errors:
        404:
          code: ResourceNotFoundException
